---
title: "Predator summary"
format:
  html:
    code-fold: true
editor: visual
output-dir: "docs"
---

```{r}
#| label: setup
#| include: false

library(targets)
library(tidyverse)

tar_load(c("predators_agg", "ant_sf"), store = here::here("_targets"))
source(here::here("R", "sp.R"))
```

## Antarctic Peninsula winter predators

### Counts

The five most abundant species.

```{r}

top_five <- predators_agg %>% 
  group_by(species) %>% 
  summarize(total_count = sum(count)) %>% 
  arrange(desc(total_count)) %>%
  slice(1:5)

top_five
```

```{r}

top_five_plot_data <- predators_agg %>% 
  semi_join(top_five, by = "species") %>% 
  group_by(year, species) %>% 
  summarize(total = sum(count), .groups = "drop") %>% 
  mutate(species = fct_reorder(species, total, .fun = sum),
         year = factor(year, levels = 2016:2012))
year_labels <- top_five_plot_data %>% 
  filter(species == "SNPT") %>% 
  arrange(desc(year)) %>%                   # Make the labels show up at
  mutate(total = cumsum(total) - total / 2) # correct y-axis position

ggplot(top_five_plot_data, aes(species, total, group = year)) +
  geom_col(color = "black", fill = "grey80") +
  geom_text(aes(label = year), year_labels) +
  labs(y = "Total species count") +
  theme_classic() +
  theme(axis.title.x = element_blank())
```

### Maps

Distribution maps of the five most abundant species in each survey year, aggregated to 50km bins.

```{r}
#| label: topfive_map
#| warning: false
#| column: screen
#| out-width: 100%
#| fig-width: 6
#| fig-dpi: 600

topfive_sf <- predators_agg %>% 
  semi_join(top_five, by = "species") %>% 
  latlon_to_sf(coords = c("lon_mean", "lat_mean"))

topfive_stars <- rasterize_counts(topfive_sf, res = 5e4)

map_lim <- sf::st_bbox(topfive_sf) %>% 
  project_bbox() %>% 
  expand_bbox(factor = 1.2)

ant_basemap(map_lim) +
  stars::geom_stars(aes(fill = count), data = topfive_stars) +
  scale_fill_gradient(low = "lightblue", high = "darkred",
                      trans = scales::pseudo_log_trans(),
                      breaks = c(0, 25, 100, 400, 1000, 4000),
                      na.value = NA) +
  scale_x_continuous(breaks = c(-65, -60, -55)) +
  scale_y_continuous(breaks = c(-64, -62, -60, -58)) +
  facet_grid(species ~ year) +
  expand_limits(fill = 0) +
  theme(axis.text.x = element_text(size = 7))
```

Distribution maps of five species of interest in each survey year, also aggregated to 50km bins.

```{r}
#| label: soi_map
#| warning: false
#| column: screen
#| out-width: 100%
#| fig-width: 6
#| fig-dpi: 600

soi <- c("GEPN", "BLPT", "ANTE", "LESE", "KIWH")

soi_sf <- predators_agg %>% 
  filter(species %in% soi) %>% 
  latlon_to_sf(coords = c("lon_mean", "lat_mean"))

soi_stars <- rasterize_counts(soi_sf, res = 5e4)

map_lim <- sf::st_bbox(soi_sf) %>% 
  project_bbox() %>% 
  expand_bbox(factor = 1.2)

ant_basemap(map_lim) +
  stars::geom_stars(aes(fill = count), data = soi_stars) +
  scale_fill_gradient(low = "lightblue", high = "darkred",
                      trans = scales::pseudo_log_trans(),
                      breaks = c(0, 25, 100, 400, 1000, 4000),
                      na.value = NA) +
  scale_x_continuous(breaks = c(-65, -60, -55)) +
  scale_y_continuous(breaks = c(-64, -62, -60, -58)) +
  facet_grid(species ~ year) +
  expand_limits(fill = 0) +
  theme(axis.text.x = element_text(size = 7))
```
