---
title: "Station summary"
format:
  html:
    code-fold: true
    toc: true
editor: visual
output-dir: "docs"
---

```{r}
#| label: setup
#| include: false

library(targets)
library(tidyverse)

tar_load(c("zoop_sf", "ant_sf"), store = here::here("_targets"))
source(here::here("R", "sp.R"))
source(here::here("R", "zoop.R"))
```

## Station maps

Sampling stations across survey years, color-coded by time-of-day. Grey circles indicate 10k, 15k, and 20k buffers.

```{r}
#| label: station_maps

zoop_buffers_10k <- sf::st_buffer(zoop_sf, 5e3)
zoop_buffers_15k <- sf::st_buffer(zoop_sf, 10e3)
zoop_buffers_20k <- sf::st_buffer(zoop_sf, 20e3)

map_lim <- sf::st_bbox(zoop_sf) %>% 
  project_bbox() %>% 
  expand_bbox(factor = 1.2)

ant_basemap(map_lim) +
  geom_sf(aes(color = time.of.day), zoop_sf, size = 0.2) +
  geom_sf(data = zoop_buffers_10k, color = "lightgrey", fill = NA) +
  geom_sf(data = zoop_buffers_15k, color = "lightgrey", fill = NA) +
  geom_sf(data = zoop_buffers_20k, color = "lightgrey", fill = NA) +
  facet_wrap(~ Year) +
  scale_x_continuous(breaks = c(-60, -55)) +
  scale_y_continuous(breaks = c(-63, -62, -61, -60)) +
  scale_color_manual(values = tod_pal()) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  coord_ant(map_lim) +
  theme(legend.position = "bottom",
        legend.title = element_blank())
```

## Zooplankton maps

```{r}
#| label: station_map_fn

station_map <- function(var, pseudolog = FALSE) {
  zoop_trans <- zoop_sf
  if (pseudolog) {
    old_var <- var 
    var <- str_glue("log({var}+1)")
    zoop_trans[[var]] <- log(zoop_trans[[old_var]] + 1)
  }
  ant_basemap(map_lim) +
    geom_sf(aes(color = .data[[var]]), zoop_trans, size = 2, shape = 15) +
    facet_wrap(~ Year) +
    scale_x_continuous(breaks = c(-60, -55)) +
    scale_y_continuous(breaks = c(-63, -62, -61, -60)) +
    { if (is.numeric(zoop_trans[[var]])) 
      scale_color_distiller(palette = "PuRd", direction = 1) } +
    coord_ant(map_lim) +
    theme(legend.position = "bottom")
}

```

```{r}
#| label: zoop_maps

zoop_vars_raw <- c("Winter Cluster factor",
                   "NMDS_x",
                   "NMDS_y",
                   "NMDS_z")
zoop_vars_pseudolog <- c("Amphipoda_Primno_N.A",
                         "Amphipoda_Themisto_N.A",
                         "Chaetognatha_N.A",
                         "Copepoda_Cacutus_N.A",
                         "Copepoda_Cprop_N.A",
                         "Copepoda_Heterorhabdus_N.A",
                         "Copepoda_Metridia_N.A",
                         "Copepoda_Paraeuchaeta_N.A",
                         "Copepoda_Pleuromama_N.A",
                         "Copepoda_Rhincalanus_N.A",
                         "Euphausiidae_Ecrystall_Adult",
                         "Euphausiidae_Efrigida_Adult",
                         "Euphausiidae_Efrigida_Larvae",
                         "Euphausiidae_Esuperba_Adult",
                         "Euphausiidae_Etricantha_Adult",
                         "Euphausiidae_Tmac_Adult",
                         "Euphausiidae_Tmac_Larvae",
                         "Gastropoda_Clione_N.A",
                         "Gastropoda_Limacina_N.A",
                         "Ostracoda_N.A",
                         "Radiolaria_N.A",
                         "Siphonophora_N.A",
                         "Tunicata_Salpa_N.A",
                         "Euphausiidae_Esuperba_F_Tot",
                         "Pisces_Paralepididae_NotolepisSpp_Larvae_Tot",
                         "Pisces_Myctophidae_Adult_Tot",
                         "Pisces_Myctophidae_Larvae_Tot",
                         "Pisces_Other_Larvae_Tot",
                         "Pisces_Chaenichthyidae_Larvae_Tot",
                         "Pisces_Nototheniidae_Larvae_Tot")

walk(zoop_vars_raw, compose(print, station_map))
walk(zoop_vars_pseudolog, 
     compose(print, partial(station_map, pseudolog = TRUE)))

```

## Physics maps

```{r}
#| label: physics_maps

physics_vars <- c("Net.ice.type",
                  "Net.ice.percent",
                  "zuml_m",
                  "avg.Dens.Diff",
                  "avg.salinity",
                  "avg.temp",
                  "Integ.chla.zuml",
                  "Integ.phae.zuml",
                  "Integ.chla.100m",
                  "Integ.phae.100m")

walk(physics_vars, compose(print, station_map))

```
