---
title: "Combined stations and predators"
format:
  html:
    code-fold: true
editor: visual
output-dir: "docs"
---

```{r}
#| label: setup
#| include: false

library(targets)
library(tidyverse)

tar_load(c("predators_agg", "zoop", "ant_sf"), 
         store = here::here("_targets"))
source(here::here("R", "sp.R"))
source(here::here("R", "zoop.R"))
```

Station locations on predator (five most abundant) count maps. Spatially restricted to station transects.

```{r}
#| label: combined_map
#| warning: false
#| column: screen
#| out-width: 100%
#| fig-width: 6
#| fig-dpi: 600

top_five <- predators_agg %>% 
  group_by(species) %>% 
  summarize(total_count = sum(count)) %>% 
  arrange(desc(total_count)) %>%
  slice(1:5)

topfive_sf <- predators_agg %>% 
  semi_join(top_five, by = "species") %>% 
  latlon_to_sf(coords = c("lon_mean", "lat_mean"))

topfive_stars <- rasterize_counts(topfive_sf, res = 2.5e4)

zoop_sf <- latlon_to_sf(zoop, 
                        coords = c("dec.longitude", "dec.latitude")) %>% 
  sf::st_transform(ant_proj()) %>% 
  rename(year = Year)
zoop_buffers_20k <- sf::st_buffer(zoop_sf, 20e3)

map_lim <- sf::st_bbox(zoop_sf) %>% 
  project_bbox() %>% 
  expand_bbox(factor = 1.2)

ant_basemap(map_lim) +
  stars::geom_stars(aes(fill = count), data = topfive_stars) +
  geom_sf(aes(color = time.of.day), zoop_sf, size = 0.2) +
  scale_x_continuous(breaks = c(-65, -60, -55)) +
  scale_y_continuous(breaks = c(-66, -64, -62, -60)) +
  scale_fill_gradient(low = "lightblue", high = "darkred",
                      trans = scales::pseudo_log_trans(),
                      breaks = c(0, 25, 100, 400, 1000, 4000),
                      na.value = NA) +
  scale_color_manual(values = tod_pal()) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  coord_ant(map_lim) +
  facet_grid(species ~ year) +
  expand_limits(fill = 0) +
  theme(axis.text.x = element_text(size = 7),
        legend.position = "bottom",
        legend.title = element_blank())
```

As above, but for species of interest (Gentoo Penguins, Blue Petrels, Antarctic Terns, Leopard Seals, and Killer Whales).

```{r}
#| label: combined_map_soi
#| warning: false
#| column: screen
#| out-width: 100%
#| fig-width: 6
#| fig-dpi: 600

soi <- c("GEPN", "BLPT", "ANTE", "LESE", "KIWH")

soi_sf <- predators_agg %>% 
  filter(species %in% soi) %>% 
  latlon_to_sf(coords = c("lon_mean", "lat_mean"))

soi_stars <- rasterize_counts(soi_sf, res = 2.5e4)

ant_basemap(map_lim) +
  stars::geom_stars(aes(fill = count), data = soi_stars) +
  geom_sf(aes(color = time.of.day), zoop_sf, size = 0.2) +
  scale_x_continuous(breaks = c(-65, -60, -55)) +
  scale_y_continuous(breaks = c(-66, -64, -62, -60)) +
  scale_fill_gradient(low = "lightblue", high = "darkred",
                      trans = scales::pseudo_log_trans(),
                      breaks = c(0, 25, 100, 400, 1000, 4000),
                      na.value = NA) +
  scale_color_manual(values = tod_pal()) +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  coord_ant(map_lim) +
  facet_grid(species ~ year) +
  expand_limits(fill = 0) +
  theme(axis.text.x = element_text(size = 7),
        legend.position = "bottom",
        legend.title = element_blank())
```
